# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTM2ZjYyNDliYzFmNjFiNGIwYTA3Y2NjZDZkMmQ3NDA3Y2VjZmQwYzYyNzRlNTkzZjFjNjFhMDczMTY1ZWJjMDA3NTQzZTE1N2Y4Y2VkNzM0MDM0ZGZkNmQzY2JlNjZlMmJlMDRkOTczNTljNTMwYjU4OGRhMDY1YzJkNDA2YmY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
